//! Golden fixture tests: every checked-in exposition body parses to its
//! hand-written expected table exactly. The expected JSON is never
//! generated by the parser under test.

use obs_scrape::parse_exposition;

#[derive(Debug, serde::Deserialize)]
struct Expected {
    malformed_lines: usize,
    samples: Vec<ExpectedSample>,
}

#[derive(Debug, serde::Deserialize)]
struct ExpectedSample {
    metric: String,
    labels_json: String,
    value: f64,
}

fn assert_golden(body: &str, expected_json: &str) {
    let expected: Expected = serde_json::from_str(expected_json).expect("valid expected json");
    let out = parse_exposition(body);
    assert_eq!(
        out.malformed_lines, expected.malformed_lines,
        "malformed count"
    );
    assert_eq!(out.samples.len(), expected.samples.len(), "sample count");
    for (i, (got, want)) in out.samples.iter().zip(&expected.samples).enumerate() {
        assert_eq!(got.metric, want.metric, "metric at index {i}");
        assert_eq!(got.labels_json, want.labels_json, "labels at index {i}");
        assert!(
            got.value == want.value,
            "value at index {i}: got {}, want {}",
            got.value,
            want.value
        );
    }
}

macro_rules! golden {
    ($name:ident, $stem:literal) => {
        #[test]
        fn $name() {
            assert_golden(
                include_str!(concat!("fixtures/", $stem, ".txt")),
                include_str!(concat!("fixtures/", $stem, ".expected.json")),
            );
        }
    };
}

golden!(determinism_hypervisor, "determinism-hypervisor");
golden!(snapshot_store, "snapshot-store");
golden!(exploration_orchestrator, "exploration-orchestrator");
golden!(state_scorer, "state-scorer");
golden!(input_synthesizer, "input-synthesizer");
golden!(replay_renderer, "replay-renderer");
golden!(control_plane, "control-plane");
golden!(malformed, "malformed");
golden!(prometheus_encoder, "prometheus-encoder");

/// Builds the exposition body the `prometheus` crate itself emits (real
/// library escaping quirks included) and asserts it matches the checked-in
/// fixture — so `prometheus-encoder.txt` can never drift from what the
/// library actually produces.
fn encode_reference_registry() -> String {
    use prometheus::{
        histogram_opts, opts, Encoder, HistogramVec, IntCounterVec, IntGauge, Registry, TextEncoder,
    };

    let registry = Registry::new();
    let counter = IntCounterVec::new(
        opts!("enc_requests_total", "Requests, with awkward label values."),
        &["route"],
    )
    .unwrap();
    counter
        .with_label_values(&["line1\nline2 \"quoted\" back\\slash"])
        .inc_by(7);
    let gauge = IntGauge::new("enc_queue_depth", "Plain gauge.").unwrap();
    gauge.set(42);
    let histogram = HistogramVec::new(
        histogram_opts!(
            "enc_latency_seconds",
            "Latency histogram.",
            vec![0.25, 0.5, 1.0]
        ),
        &["stage"],
    )
    .unwrap();
    for v in [0.1, 0.3, 0.9, 2.0] {
        histogram.with_label_values(&["encode"]).observe(v);
    }
    registry.register(Box::new(counter)).unwrap();
    registry.register(Box::new(gauge)).unwrap();
    registry.register(Box::new(histogram)).unwrap();

    let mut buf = Vec::new();
    TextEncoder::new()
        .encode(&registry.gather(), &mut buf)
        .unwrap();
    String::from_utf8(buf).unwrap()
}

#[test]
fn prometheus_encoder_fixture_is_in_sync() {
    assert_eq!(
        encode_reference_registry(),
        include_str!("fixtures/prometheus-encoder.txt"),
        "fixture drifted from the prometheus crate's own TextEncoder output"
    );
}
